# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


# azure-pipelines.yml  ── place at the repo root
trigger:
  branches:
      include:
            - main          # <-- branch you push to

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: pom.xml          # path to pom.xml (adjust if nested)
      goals: clean install           # no quotes needed
      publishJUnitResults: true


